name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=&9^mm5kcrynh+%prc=txebe8s5)k7l+u2%o)nrs@wqmy=0&2wx
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=wEUpTs7xW1OTmYPwN2bLMFMZ
      - PASSAGE_API_KEY=XYkd33Hryl.naT5Ygp6SlecrSCa8KQm2iwNwU4CJ3aCVef7UcneaHeK0RmZoLP4dO2FyRBhPnMi

    ports:
      - 8000:8000